# SwiftLint Configuration for MacUIKit

# 包含的文件路径
included:
  - Sources
  - Tests
  - Examples

# 排除的文件路径
excluded:
  - .build
  - Packages
  - DerivedData
  - .swiftpm

# 禁用的规则
disabled_rules:
  - trailing_whitespace
  - todo
  - line_length # 我们将自定义行长度

# 启用的可选规则
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# 自定义规则配置
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

cyclomatic_complexity:
  warning: 10
  error: 20

file_length:
  warning: 400
  error: 1000
  ignore_comment_only_lines: true

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 60
    error: 60
  excluded:
    - id
    - url
    - uri

type_name:
  min_length:
    warning: 3
    error: 3
  max_length:
    warning: 60
    error: 60

# 文件头部注释规则
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  MacUIKit
                    \/\/
                    \/\/  Created by .* on \d{4}\/\d{2}\/\d{2}\.
                    \/\/  Copyright © \d{4} MacUIKit\. All rights reserved\.
                    \/\/

# 自定义规则
custom_rules:
  # 组件命名规则
  component_naming:
    name: "Component Naming"
    regex: '^(public )?struct Mac[A-Z][a-zA-Z]*: View'
    message: "UI组件应该以'Mac'为前缀，如MacButton"
    severity: warning

  # 禁止使用print语句
  no_print:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    message: "请使用Logger替代print语句"
    severity: warning

  # 确保视图修饰符的正确顺序
  modifier_order:
    name: "Modifier Order"
    regex: '\.padding\([^)]*\)\s*\.background'
    message: "padding应该在background之后"
    severity: warning
