name: Feature Request
description: 建议一个新功能或改进
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的功能建议！让我们一起让MacUIKit变得更好。
        
  - type: textarea
    id: problem
    attributes:
      label: 问题描述
      description: 您的功能请求是否与某个问题相关？请描述一下。
      placeholder: 我总是为...而感到沮丧，当...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 您希望发生什么？
      placeholder: 清晰简洁地描述您想要的功能。
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: 考虑过的替代方案
      description: 您是否考虑过其他替代解决方案或功能？
      placeholder: 清晰简洁地描述您考虑过的任何替代解决方案或功能。
      
  - type: dropdown
    id: component_type
    attributes:
      label: 组件类型
      description: 这个功能属于哪个组件类型？
      options:
        - 基础组件 (Basic Components)
        - 布局组件 (Layout Components)
        - 反馈组件 (Feedback Components)
        - 高级组件 (Advanced Components)
        - 主题系统 (Theme System)
        - 工具类 (Utilities)
        - 其他 (Other)
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: 优先级
      description: 您认为这个功能的优先级如何？
      options:
        - 低 (Low)
        - 中 (Medium)
        - 高 (High)
        - 紧急 (Critical)
    validations:
      required: true
      
  - type: textarea
    id: additional
    attributes:
      label: 附加信息
      description: |
        添加任何其他关于功能请求的上下文信息或截图。
        提示：您可以拖拽图片到这里添加截图。
